{{- if .Values.secretConfiguration.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "external-dns.fullname" . }}
  namespace: {{ include "external-dns.namespace" . }}
  labels:
    {{- include "external-dns.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.secretConfiguration.data }}
  {{ $key }}: {{ tpl $value $ | b64enc | quote }}
{{- end }}
{{- end }}
